name: zipcodeph_flutter
description: 'ZIP Code PH built on Flutter'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+2023120401

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1

  cupertino_icons: ^1.0.8
  connectivity_plus: ^7.0.0
  fluentui_system_icons: ^1.1.273
  flutter_search_bar: ^3.0.0
  google_fonts: ^6.3.2
  lottie: ^3.3.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  responsive_framework: ^1.5.1
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.2

  http: ^1.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ncr.jpg
    - assets/images/luzon.jpg
    - assets/images/visayas.jpg
    - assets/images/mindanao.jpg
    - assets/images/notfound.png
    - assets/images/empty.png
    - assets/images/notfound_only.png
    - assets/images/notfound.svg
    - assets/zips_ph.db
    - assets/json/trivias.json
    - assets/json/openbook.json
