class AreaRepository {
  List<String> menu(String area) {
    switch (area) {
      case "Metro Manila":
        return [
          "Manila",
          "Caloocan",
          "Las Piñas",
          "Makati",
          "Malabon",
          "Mandaluyong",
          "Marikina",
          "Navotas",
          "Parañaque",
          "Pasay",
          "Pasig",
          "Pateros",
          "Quezon City",
          "San Juan",
          "Taguig",
          "Valenzuela"
        ];
      case "Luzon":
        return [
          "Abra",
          "Albay",
          "Apayao",
          "Aurora",
          "Bataan",
          "Batanes",
          "Batangas",
          "Benguet",
          "Bulacan",
          "Cagayan",
          "Camarines Norte",
          "Camarines Sur",
          "Catanduanes",
          "Cavite",
          "Ifugao",
          "Ilocos Norte",
          "Ilocos Sur",
          "Isabela",
          "Kalinga",
          "La Union",
          "Laguna",
          "Marinduque",
          "Masbate",
          "Mountain Province",
          "Nueva Ecija",
          "Nueva Vizcaya",
          "Occidental Mindoro",
          "Oriental Mindoro",
          "Palawan",
          "Pampanga",
          "Pangasinan",
          "Quezon",
          "Quirino",
          "Rizal",
          "Romblon",
          "Sorsogon",
          "Tarlac",
          "Zambales",
        ];
      case "Visayas":
        return [
          "Aklan",
          "Antique",
          "Biliran",
          "Bohol",
          "Capiz",
          "Cebu",
          "Eastern Samar",
          "Guimaras",
          "Iloilo",
          "Leyte",
          "Negros Occidental",
          "Negros Oriental",
          "Northern Samar",
          "Samar",
          "Siquijor",
          "Southern Leyte",
        ];
      case "Mindanao":
        return [
          "Agusan del Norte",
          "Agusan del Sur",
          "Basilan",
          "Bukidnon",
          "Camiguin",
          "Compostela Valley",
          "Davao del Norte",
          "Davao del Sur",
          "Davao Occidental",
          "Davao Oriental",
          "Dinagat Islands",
          "Lanao del Norte",
          "Lanao del Sur",
          "Maguindanao",
          "Misamis Occidental",
          "Misamis Oriental",
          "North Cotabato",
          "South Cotabato",
          "Sultan Kudarat",
          "Sulu",
          "Surigao del Norte",
          "Surigao del Sur",
          "Tawi-Tawi",
          "Zamboanga del Norte",
          "Zamboanga del Sur",
          "Zamboanga Sibugay",
        ];
    }

    return [];
  }
}
